# general setting
batch_size: 8
input_shape: [224, 224, 1]
crop_size: [224, 224]

# training dataset
dataset_path: './dataset/border'
dataset_len: 298  # number of training samples

# training setting
epoch: 1000
init_lr: !!float 1e-2
decay_rate: 0.96
decay_steps: 100
warmup_epoch: 5
min_lr: !!float 1e-3
weights_decay: !!float 5e-4
momentum: 0.9

checkpoint_dir: './logs/checkpoints'
